# Generated by Django 3.1.7 on 2021-03-20 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tanks', 'Танки'), ('hills', 'Хилы'), ('dd', 'ДД'), ('Merchants', 'Торговцы'), ('Guildmasters', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('Zelievars', 'Зельевары'), ('SpellMasters', 'Мастера заклинаний')], default='tanks', max_length=25, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата пуболткации')),
                ('file', models.FileField(blank=True, null=True, upload_to='bulletin_file/', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Изобнажение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.category', verbose_name='категория')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользыватель')),
            ],
            options={
                'verbose_name': 'Обявление',
                'verbose_name_plural': 'Обявления',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=3000, verbose_name='Отклик')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='коментатор')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.declaration', verbose_name='обявление')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
