# Generated by Django 3.1.7 on 2021-03-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20210321_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='declaration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.author', verbose_name='Пользыватель'),
        ),
    ]
