# Generated by Django 3.1.7 on 2021-04-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_auto_20210405_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.author', verbose_name='Пользыватель'),
        ),
    ]
