# Generated by Django 3.1.7 on 2021-04-17 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0007_auto_20210417_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='reviews',
            field=models.ManyToManyField(related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='отклик'),
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='declaration',
        ),
        migrations.AddField(
            model_name='reviews',
            name='declaration',
            field=models.ManyToManyField(related_name='review_declaration', to=settings.AUTH_USER_MODEL, verbose_name='обявление'),
        ),
    ]
