# Generated by Django 3.1.7 on 2021-04-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0008_auto_20210417_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='declaration',
        ),
        migrations.AddField(
            model_name='declaration',
            name='review',
            field=models.ManyToManyField(related_name='declaration_review', to='bulletin.Reviews', verbose_name='отзывы'),
        ),
    ]
