# Generated by Django 3.1.7 on 2021-04-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20210417_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='review',
            new_name='reviiew',
        ),
    ]
