# Generated by Django 3.1.7 on 2021-04-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0010_auto_20210417_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='review',
        ),
        migrations.AddField(
            model_name='declaration',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaration_review', to='bulletin.reviews', verbose_name='отзывы'),
        ),
    ]
