# Generated by Django 3.1.7 on 2021-04-24 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0012_auto_20210418_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='accepted_responses',
            field=models.ManyToManyField(related_name='post_accepted_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaration',
            name='responses',
            field=models.ManyToManyField(related_name='post_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
