# Generated by Django 3.1.7 on 2021-04-24 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0013_auto_20210424_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaration',
            name='accepted_responses',
        ),
        migrations.RemoveField(
            model_name='declaration',
            name='responses',
        ),
        migrations.AddField(
            model_name='declaration',
            name='accepted_response',
            field=models.ManyToManyField(related_name='post_accepted_response', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaration',
            name='response',
            field=models.ManyToManyField(related_name='post_response', to=settings.AUTH_USER_MODEL),
        ),
    ]
